apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: nextcloud
  name: nextcloud
spec:
  type: 'LoadBalancer'
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    io.kompose.service: nextcloud
